package components

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"
)

func write(t testing.TB, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func reg(typeExpr, name string) string {
	return fmt.Sprintf("<?php\nuse Magento\\Framework\\Component\\ComponentRegistrar;\nComponentRegistrar::register(%s, '%s', __DIR__);\n", typeExpr, name)
}

// fakeStore builds a small Magento tree and returns its (symlink-resolved) root.
func fakeStore(t *testing.T) string {
	base, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(base, "vendor/composer/autoload_files.php"), `<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'a4a119a56e50fbb293281d9a48007e0e' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    '11111111111111111111111111111111' => $vendorDir . '/magento/module-catalog/registration.php',
    '22222222222222222222222222222222' => $vendorDir . '/magento/theme-frontend-luma/registration.php',
    '33333333333333333333333333333333' => $vendorDir . '/magento/module-missing/registration.php',
    '44444444444444444444444444444444' => $vendorDir . '/hyva/theme/registration.php',
    '55555555555555555555555555555555' => $vendorDir . '/magento/framework/registration.php',
    '66666666666666666666666666666666' => $vendorDir . '/magento/language-nl_nl/registration.php',
    '77777777777777777777777777777777' => $vendorDir . '/acme/multi/registration.php',
    '88888888888888888888888888888888' => $vendorDir . '/acme/broken/registration.php',
    '99999999999999999999999999999999' => $vendorDir . '/acme/dup/registration.php',
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' => $vendorDir . '/acme/super/registration.php',
    '4887019506f275125b720bf9bcfdc406' => $baseDir . '/app/etc/NonComposerComponentRegistration.php',
);
`)
	write(t, filepath.Join(base, "vendor/magento/module-catalog/registration.php"), reg("ComponentRegistrar::MODULE", "Magento_Catalog"))
	write(t, filepath.Join(base, "vendor/magento/theme-frontend-luma/registration.php"),
		"<?php\n\\Magento\\Framework\\Component\\ComponentRegistrar::register(\n  \\Magento\\Framework\\Component\\ComponentRegistrar::THEME,\n  \"frontend/Magento/luma\",\n  __DIR__\n);\n")
	write(t, filepath.Join(base, "vendor/hyva/theme/registration.php"),
		"<?php\ndeclare(strict_types=1);\nuse Magento\\Framework\\Component\\ComponentRegistrar as R;\n\nR::register(R::THEME, 'frontend/Hyva/default', __DIR__ . '/src');\n")
	if err := os.MkdirAll(filepath.Join(base, "vendor/hyva/theme/src"), 0o755); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(base, "vendor/magento/framework/registration.php"), reg("ComponentRegistrar::LIBRARY", "magento/framework"))
	write(t, filepath.Join(base, "vendor/magento/language-nl_nl/registration.php"), reg("ComponentRegistrar::LANGUAGE", "magento_nl_nl"))
	write(t, filepath.Join(base, "vendor/acme/multi/registration.php"), "<?php\n"+
		"use Magento\\Framework\\Component\\ComponentRegistrar;\n"+
		"// ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Acme_Commented', __DIR__);\n"+
		"/* ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Acme_Commented2', __DIR__); */\n"+
		"ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Acme_One', __DIR__ . '/One');\n"+
		"ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Acme_Two', __DIR__ . \"/Two\",);\n")
	write(t, filepath.Join(base, "vendor/acme/broken/registration.php"), "<?php\n// nothing here\n")
	write(t, filepath.Join(base, "vendor/acme/dup/registration.php"), reg("ComponentRegistrar::MODULE", "Magento_Catalog"))
	// A "superpackage" whose registration.php only includes others.
	write(t, filepath.Join(base, "vendor/acme/super/registration.php"),
		"<?php\n$regs = [\n  'app/code/Acme/SubA/registration.php',\n  \"app/code/Acme/SubB/registration.php\",\n];\nforeach ($regs as $f) { require_once __DIR__ . '/' . $f; }\n")
	write(t, filepath.Join(base, "vendor/acme/super/app/code/Acme/SubA/registration.php"), reg("ComponentRegistrar::MODULE", "Acme_SubA"))
	write(t, filepath.Join(base, "vendor/acme/super/app/code/Acme/SubB/registration.php"), reg("ComponentRegistrar::MODULE", "Acme_SubB"))

	write(t, filepath.Join(base, "app/etc/NonComposerComponentRegistration.php"), "<?php\n")
	write(t, filepath.Join(base, "app/code/Acme/Local/registration.php"), reg("ComponentRegistrar::MODULE", "Acme_Local"))
	write(t, filepath.Join(base, "app/code/Acme/Local/cli_commands.php"), "<?php\n")
	write(t, filepath.Join(base, "app/design/frontend/Acme/shop/registration.php"), reg("ComponentRegistrar::THEME", "frontend/Acme/shop"))
	write(t, filepath.Join(base, "app/design/adminhtml/Acme/admin/registration.php"), reg("'theme'", "adminhtml/Acme/admin"))

	// A module symlinked into app/code from elsewhere.
	ext := filepath.Join(base, "external/linked-module")
	write(t, filepath.Join(ext, "registration.php"), reg("ComponentRegistrar::MODULE", "Acme_Linked"))
	if err := os.MkdirAll(filepath.Join(base, "app/code/Acme"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(ext, filepath.Join(base, "app/code/Acme/Linked")); err != nil {
		t.Fatal(err)
	}
	return base
}

func TestDiscover(t *testing.T) {
	base := fakeStore(t)
	comps, warnings, err := DiscoverWithWarnings(base)
	if err != nil {
		t.Fatal(err)
	}
	v := func(p string) string { return filepath.Join(base, p) }
	want := []Component{
		{Language, "magento_nl_nl", v("vendor/magento/language-nl_nl")},
		{Library, "magento/framework", v("vendor/magento/framework")},
		{Module, "Acme_Linked", v("external/linked-module")},
		{Module, "Acme_Local", v("app/code/Acme/Local")},
		{Module, "Acme_One", v("vendor/acme/multi/One")},
		{Module, "Acme_SubA", v("vendor/acme/super/app/code/Acme/SubA")},
		{Module, "Acme_SubB", v("vendor/acme/super/app/code/Acme/SubB")},
		{Module, "Acme_Two", v("vendor/acme/multi/Two")},
		{Module, "Magento_Catalog", v("vendor/magento/module-catalog")},
		{Theme, "adminhtml/Acme/admin", v("app/design/adminhtml/Acme/admin")},
		{Theme, "frontend/Acme/shop", v("app/design/frontend/Acme/shop")},
		{Theme, "frontend/Hyva/default", v("vendor/hyva/theme/src")},
		{Theme, "frontend/Magento/luma", v("vendor/magento/theme-frontend-luma")},
	}
	if !reflect.DeepEqual(comps, want) {
		t.Errorf("got:\n%s\nwant:\n%s", dump(comps), dump(want))
	}
	joined := strings.Join(warnings, "\n")
	if !strings.Contains(joined, "module-missing") || !strings.Contains(joined, "acme/broken") {
		t.Errorf("expected warnings for missing and broken registration files, got %q", warnings)
	}
}

func TestDiscoverCustomGloblistAndNoNonComposer(t *testing.T) {
	base := fakeStore(t)
	write(t, filepath.Join(base, "app/etc/registration_globlist.php"), "<?php\nreturn ['app/code/*/*/registration.php'];\n")
	comps, err := Discover(base)
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range comps {
		if c.Name == "frontend/Acme/shop" {
			t.Errorf("custom globlist ignored: %v", c)
		}
	}
	// Without NonComposerComponentRegistration.php in autoload_files, app/code is not scanned.
	af := filepath.Join(base, "vendor/composer/autoload_files.php")
	data, _ := os.ReadFile(af)
	write(t, af, strings.Replace(string(data), "NonComposerComponentRegistration.php", "Other.php", 1))
	comps, err = Discover(base)
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range comps {
		if strings.HasPrefix(c.Name, "Acme_L") {
			t.Errorf("app/code scanned without NonComposerComponentRegistration: %v", c)
		}
	}
}

func TestDiscoverCustomVendorDir(t *testing.T) {
	base := fakeStore(t)
	if err := os.Rename(filepath.Join(base, "vendor"), filepath.Join(base, "deps")); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(base, "composer.json"), `{"config": {"vendor-dir": "deps"}}`)
	comps, err := Discover(base)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, c := range comps {
		if c.Name == "Magento_Catalog" && c.Dir == filepath.Join(base, "deps/magento/module-catalog") {
			found = true
		}
	}
	if !found {
		t.Errorf("Magento_Catalog not found in custom vendor dir:\n%s", dump(comps))
	}
}

func TestDiscoverMissingAutoload(t *testing.T) {
	if _, err := Discover(t.TempDir()); err == nil {
		t.Fatal("expected error for missing autoload_files.php")
	}
}

func TestParseRegistrationVariants(t *testing.T) {
	dir := t.TempDir()
	tests := []struct {
		src      string
		wantType Type
		wantName string
	}{
		{"<?php ComponentRegistrar::register(ComponentRegistrar::MODULE,'A_B',__DIR__);", Module, "A_B"},
		{"<?php\n\\Magento\\Framework\\Component\\ComponentRegistrar::register(\\Magento\\Framework\\Component\\ComponentRegistrar::MODULE, \"A_C\", __DIR__);", Module, "A_C"},
		{"<?php\nuse Magento\\Framework\\Component\\ComponentRegistrar as CR;\nCR::register(CR::SETUP, 'magento/setup', __DIR__);", Setup, "magento/setup"},
		{"<?php\nComponentRegistrar::register(\n\tComponentRegistrar::THEME,\n\t'frontend/X/y',\n\t__DIR__\n);", Theme, "frontend/X/y"},
		{"<?php Magento\\Framework\\Component\\ComponentRegistrar::register('module', 'A_D', __DIR__);", Module, "A_D"},
	}
	for i, tt := range tests {
		p := filepath.Join(dir, fmt.Sprint(i), "registration.php")
		write(t, p, tt.src)
		cs, err := ParseRegistration(p)
		if err != nil {
			t.Errorf("case %d: %v", i, err)
			continue
		}
		if len(cs) != 1 || cs[0].Type != tt.wantType || cs[0].Name != tt.wantName {
			t.Errorf("case %d: got %v", i, cs)
		}
	}
}

func TestParseRegistrationIncludes(t *testing.T) {
	dir, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(dir, "registration.php"), "<?php\n"+
		"require __DIR__ . '/src/registration.php'; // include the main module\n"+
		"foreach (glob(__DIR__ . '/mods/*/registration.php') as $f) { require $f; }\n"+
		"/* ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Acme_Commented', __DIR__); */\n")
	write(t, filepath.Join(dir, "src/registration.php"), reg("ComponentRegistrar::MODULE", "Acme_Main"))
	write(t, filepath.Join(dir, "mods/X/registration.php"), reg("ComponentRegistrar::MODULE", "Acme_X"))
	cs, err := ParseRegistration(filepath.Join(dir, "registration.php"))
	if err != nil {
		t.Fatal(err)
	}
	want := []Component{
		{Module, "Acme_Main", filepath.Join(dir, "src")},
		{Module, "Acme_X", filepath.Join(dir, "mods/X")},
	}
	if !reflect.DeepEqual(cs, want) {
		t.Errorf("got:\n%s\nwant:\n%s", dump(cs), dump(want))
	}
}

func TestFromDump(t *testing.T) {
	base := fakeStore(t)
	if _, ok, err := FromDump(base); ok || err != nil {
		t.Fatalf("expected ok=false without dump, got ok=%v err=%v", ok, err)
	}
	write(t, filepath.Join(base, "var/cache-clean-config.json"), fmt.Sprintf(`{
		"app": {"cache": {}},
		"modules": ["vendor/magento/module-catalog", %q, "app/code/Nope/Gone"],
		"themes": ["app/design/frontend/Acme/shop"]
	}`, filepath.Join(base, "app/code/Acme/Local")))
	comps, ok, err := FromDump(base)
	if err != nil || !ok {
		t.Fatalf("ok=%v err=%v", ok, err)
	}
	want := []Component{
		{Module, "Acme_Local", filepath.Join(base, "app/code/Acme/Local")},
		{Module, "Magento_Catalog", filepath.Join(base, "vendor/magento/module-catalog")},
		{Module, "Nope_Gone", filepath.Join(base, "app/code/Nope/Gone")},
		{Theme, "frontend/Acme/shop", filepath.Join(base, "app/design/frontend/Acme/shop")},
	}
	if !reflect.DeepEqual(comps, want) {
		t.Errorf("got:\n%s\nwant:\n%s", dump(comps), dump(want))
	}
}

func dump(cs []Component) string {
	var b strings.Builder
	for _, c := range cs {
		fmt.Fprintf(&b, "  %s %s %s\n", c.Type, c.Name, c.Dir)
	}
	return b.String()
}

func realSites(t testing.TB) []string {
	home, err := os.UserHomeDir()
	if err != nil {
		t.Skip("no home dir")
	}
	sites, _ := filepath.Glob(filepath.Join(home, "sites", "*", "vendor", "magento", "framework", "registration.php"))
	var out []string
	for _, s := range sites {
		out = append(out, filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(s)))))
	}
	if len(out) == 0 {
		t.Skip("no Magento installs found under ~/sites")
	}
	sort.Strings(out)
	return out
}

const phpRegistrarCode = `require $argv[1]."/vendor/autoload.php"; $r=new \Magento\Framework\Component\ComponentRegistrar; echo "\n__MCC__".json_encode(["module"=>$r->getPaths("module"),"theme"=>$r->getPaths("theme")]);`

// TestRealSites compares Discover with PHP's ComponentRegistrar for every
// Magento install under ~/sites. Only counts and component names are printed.
func TestRealSites(t *testing.T) {
	if _, err := exec.LookPath("php"); err != nil {
		t.Skip("php not available")
	}
	for _, base := range realSites(t) {
		t.Run(filepath.Base(base), func(t *testing.T) {
			start := time.Now()
			comps, warnings, err := DiscoverWithWarnings(base)
			elapsed := time.Since(start)
			if err != nil {
				t.Fatalf("Discover: %v", err)
			}

			cmd := exec.Command("php", "-r", phpRegistrarCode, "--", base)
			var stdout bytes.Buffer
			cmd.Stdout = &stdout
			_ = cmd.Run()
			out := stdout.Bytes()
			i := bytes.LastIndex(out, []byte("__MCC__"))
			if i < 0 {
				t.Skipf("php ComponentRegistrar failed (native found %d components in %v)", len(comps), elapsed)
			}
			var phpRes map[string]map[string]string
			if err := json.Unmarshal(out[i+len("__MCC__"):], &phpRes); err != nil {
				t.Skipf("php output not decodable: %v", err)
			}

			native := map[string]map[string]string{"module": {}, "theme": {}}
			for _, c := range comps {
				if m, ok := native[string(c.Type)]; ok {
					m[c.Name] = c.Dir
				}
			}
			for _, typ := range []string{"module", "theme"} {
				phpSet := phpRes[typ]
				var onlyNative, onlyPHP, dirDiff []string
				for name, dir := range native[typ] {
					pdir, ok := phpSet[name]
					if !ok {
						onlyNative = append(onlyNative, name)
						continue
					}
					if resolve(pdir) != dir {
						dirDiff = append(dirDiff, name)
					}
				}
				for name := range phpSet {
					if _, ok := native[typ][name]; !ok {
						onlyPHP = append(onlyPHP, name)
					}
				}
				sort.Strings(onlyNative)
				sort.Strings(onlyPHP)
				sort.Strings(dirDiff)
				t.Logf("%s: native=%d php=%d", typ, len(native[typ]), len(phpSet))
				if len(onlyNative) > 0 {
					t.Errorf("%s only found natively (%d): %v", typ, len(onlyNative), onlyNative)
				}
				if len(onlyPHP) > 0 {
					t.Errorf("%s only found by php (%d): %v", typ, len(onlyPHP), onlyPHP)
				}
				if len(dirDiff) > 0 {
					t.Errorf("%s with different dir (%d): %v", typ, len(dirDiff), dirDiff)
				}
			}
			t.Logf("discovered %d components in %v (%d warnings)", len(comps), elapsed, len(warnings))
			for _, w := range warnings {
				t.Logf("warning: %s", strings.ReplaceAll(w, base+string(filepath.Separator), ""))
			}
		})
	}
}

func BenchmarkDiscoverRealSites(b *testing.B) {
	for _, base := range realSites(b) {
		b.Run(filepath.Base(base), func(b *testing.B) {
			for b.Loop() {
				if _, err := Discover(base); err != nil {
					b.Fatal(err)
				}
			}
		})
	}
}

func BenchmarkDiscoverFake(b *testing.B) {
	base, _ := filepath.EvalSymlinks(b.TempDir())
	write(b, filepath.Join(base, "app/etc/NonComposerComponentRegistration.php"), "<?php\n")
	var af strings.Builder
	af.WriteString("<?php\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\nreturn array(\n")
	for i := range 600 {
		rel := fmt.Sprintf("/vendor%d/module-%d/registration.php", i%20, i)
		fmt.Fprintf(&af, "    '%032d' => $vendorDir . '%s',\n", i, rel)
		write(b, filepath.Join(base, "vendor", rel), reg("ComponentRegistrar::MODULE", fmt.Sprintf("V%d_M%d", i%20, i)))
	}
	af.WriteString("    'x' => $baseDir . '/app/etc/NonComposerComponentRegistration.php',\n);\n")
	write(b, filepath.Join(base, "vendor/composer/autoload_files.php"), af.String())
	b.ResetTimer()
	for b.Loop() {
		cs, err := Discover(base)
		if err != nil || len(cs) != 600 {
			b.Fatalf("got %d components, err %v", len(cs), err)
		}
	}
}
